name: main_student-mentor-protege-system

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend   # 👈 change this to your actual frontend folder
        run: npm install

      - name: Build
        working-directory: ./frontend   # 👈 same here
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/dist         # or ./frontend/build (depending on your framework)
